### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Huan-Bao** [m-kahla/Label-Only-Model-Inversion-Attacks-via-Boundary-Repulsion#1]
I use the command from readme.
Why can't the reconstructed images correspond to the images in the CelebA dataset?
Maybe I'm using a wrong dataset?
What is the reconstructed original image dataset?
Can you answer it for me.

**Comment by m-kahla** [comment]
Hello, we have a private list of identities. The identity number 0 in our private dataset doesn't correspond to identity 0 in CelebA but to another identity number. The mapping between private identities and their corresponding ones is attached.
[private_list_1000.txt](https://github.com/m-kahla/Label-Only-Model-Inversion-Attacks-via-Boundary-Repulsion/files/10479979/private_list_1000.txt)
