### ISSUE TITLE
Facescrub and Pubfig83 experiments

### ISSUE THREAD

**Issue by ngoc-nguyen-0** [m-kahla/Label-Only-Model-Inversion-Attacks-via-Boundary-Repulsion#2]
Hi,
Could you please share the **pretrained models** and the **IDs list** (public and private images) for Facescrub and Pubfig83 experiments? 
Thank you very much.
Ngoc

**Comment by m-kahla** [comment]
Sure. Here are the target, evaluator models and the private lists of both datasets: 
https://drive.google.com/file/d/12oYvpv3HsK7cPw9NysvVywxQiBA3UVAJ/view?usp=sharing
https://drive.google.com/file/d/1gY-nOOCDxxswwtbmI4e00ySNst5lP_49/view?usp=sharing
https://drive.google.com/file/d/1sjOkS0vFUdYjgsqAEmwjvcl_MCGhyFgb/view?usp=sharing
https://drive.google.com/file/d/1Hyc3RnB_uiMStaLgI1w_BQHkVetu6EfB/view?usp=sharing
[pubfig private idens names.txt](https://github.com/m-kahla/Label-Only-
[private_train_list.txt](https://github.com/m-kahla/Label-Only-Model-Inversion-Attacks-via-Boundary-Repulsion/files/10480024/private_train_list.txt)
Model-Inversion-Attacks-via-Boundary-Repulsion/files/10480012/pubfig.private.idens.names.txt)
